theme: minima
title: Shihab Ahmed
description: Computational researcher studying molecular simulation, oxidation chemistry, tribology, and scientific machine learning.

author: Shihab Ahmed
email: sahmed73@ucmerced.edu

header_pages:
  - research.md
  - publications.md
  - blog.md
  - about.md

plugins:
  - jekyll-feed

github_username: sahmed73
linkedin_username: shihab73
