theme: minima
title: Shihab Ahmed
description: PhD Candidate in Mechanical Engineering studying molecular simulation, oxidation chemistry, and scientific machine learning.

author: Shihab Ahmed
email: sahmed73@ucmerced.edu

header_pages:
  - about.md
  - publications.md
  - blog.md

plugins:
  - jekyll-feed

minima:
  skin: dark
